---
swagger: "2.0"
info:
  description: "orms powered Web API"
  version: "1.0.0"
  title: orms API
  x-testfloatval: 5.0
  x-domain: dummy.com
  x-website: /site
  x-localhost: localhost:3000
  x-legacy: http://old.dummy.com/api/v1
host: localhost:3000
schemes:
- http
produces:
- application/json
basePath: /api/v1
paths:
  /users:
    get:
      operationId: users
      tags:
      - "Users"
      summary: "{'ttl':0,'xttl':0,'cachekey':'','xcachekey':''}"
      description: "Users"
      parameters:
      - name: "someheaderkey"
        in: "header"
        description: "Some Key Id"
        required: false
        type: "string"
      responses:
        200:
          description: "200 is returned"
definitions:
  Users:
    type: "object"
    properties:
      result:
        type: "array"
        items:
          $ref: "#/definitions/User"
  User:
    x-table: 'users'
    type: "object"
    properties:
      id:
        x-dto-field: 'user_id'
        type: "integer"
        description: "Unique identifier representing a specific user"
      name:
        x-dto-field: 'user_name'
        type: "string"
        description: "Name of user."
  SampleId:
    type: "integer"
    description: "sample integer id"
  SampleKey:
    type: "string"
    description: "sample string key"